# Generated by Django 4.1.1 on 2022-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='avatar',
            field=models.CharField(default='https://www.gravatar.com/avatar/?s=200&r=pg&d=mp', max_length=300),
        ),
    ]
