# Generated by Django 4.1.1 on 2022-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0002_alter_autor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
